<!-- <h2>UI komponente: Komunikacija između UI Komponenti </h2> -->

<!-- <script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "myUiComponent": {
                    "component": "Inchoo_UiPool/js/Primjer2/myUiComponent",
                    "template": "Inchoo_UiPool/Primjer2/table"
                }
            }
        }
    }
}
</script>

<div data-bind="scope: 'myUiComponent'">
    <h3 data-bind="text: label">Placeholder prije inicijalizacije</h3>
    <div data-bind="template: getTemplate()"></div>
    <hr>
    <p>Rabat: <span data-bind="text: fee"></span></p>
    <p>Ukupna cijena u Skladištu s rabatom: <span data-bind="text: totalPrice()"></span></p>
</div> -->

<!-- <script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "component-a": {
                    "component": "Inchoo_UiPool/js/Primjer2/component-a",
                    "children": {
                        "component-c": {
                            "component": "Inchoo_UiPool/js/Primjer2/component-c"
                        }
                    }
                },
                "component-b": {
                    "component": "Inchoo_UiPool/js/Primjer2/component-b"
                }
            }
        }
    }
}
</script>

<div data-bind="scope: 'component-a'">
    <h3 data-bind="text: label"></h3>
    <div data-bind="text: 'amount: ' + amount"></div>
</div>

<div data-bind="scope: 'component-b'">
    <h3 data-bind="text: label"></h3>
    <div data-bind="text: 'value: ' + value"></div>
</div> -->
